name: test_web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_web:
    runs-on: ubuntu-latest
    env:
      TEST_ENDPOINT: dapp-near-ref-ui.test.onekey.so
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Install Dependency
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn
      - name: Build Target
        run: |
          yarn build-gh-pages
          cp ./dist/index.html ./dist/404.html
      - name: Deploy Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: ${{ env.TEST_ENDPOINT }}
          force_orphan: true
